
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem roverprob4213)
    (:domain Rover)

    (:objects
        camera0 camera1 - camera
        general - lander
        colour high_res low_res - mode
        objective0 objective1 - objective
        rover0 - rover
        rover0store - store
        waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
    )

    (:init
        (domain1_visible waypoint2 waypoint1)
        (domain1_visible waypoint0 waypoint1)
        (domain1_visible waypoint3 waypoint0)
        (domain1_visible waypoint3 waypoint2)
        (domain1_visible waypoint0 waypoint3)
        (domain1_visible waypoint1 waypoint0)
        (domain1_visible waypoint1 waypoint2)
        (domain1_visible waypoint1 waypoint3)
        (domain1_visible waypoint0 waypoint2)
        (domain1_visible waypoint3 waypoint1)
        (domain1_visible waypoint2 waypoint3)
        (domain1_visible waypoint2 waypoint0)
        (domain1_at_soil_sample waypoint0)
        (domain1_at_rock_sample waypoint0)
        (domain1_at_lander general waypoint1)
        (domain1_channel_free general)
        (domain1_at rover0 waypoint0)
        (domain1_available rover0)
        (domain1_store_of rover0store rover0)
        (domain1_empty rover0store)
        (domain1_equipped_for_soil_analysis rover0)
        (domain1_equipped_for_rock_analysis rover0)
        (domain1_equipped_for_imaging rover0)
        (domain1_can_traverse rover0 waypoint0 waypoint2)
        (domain1_can_traverse rover0 waypoint3 waypoint0)
        (domain1_can_traverse rover0 waypoint0 waypoint1)
        (domain1_can_traverse rover0 waypoint1 waypoint0)
        (domain1_can_traverse rover0 waypoint2 waypoint0)
        (domain1_can_traverse rover0 waypoint0 waypoint3)
        (domain1_on_board camera0 rover0)
        (domain1_on_board camera1 rover0)
        (domain1_calibration_target camera0 objective0)
        (domain1_calibration_target camera1 objective1)
        (domain1_supports camera1 high_res)
        (domain1_supports camera0 colour)
        (domain1_supports camera0 high_res)
        (domain1_supports camera0 low_res)
        (domain1_visible_from objective1 waypoint1)
        (domain1_visible_from objective1 waypoint0)
        (domain1_visible_from objective0 waypoint0)
        (domain1_visible_from objective1 waypoint2)
        (domain2_visible waypoint3 waypoint0)
        (domain2_visible waypoint2 waypoint1)
        (domain2_visible waypoint0 waypoint1)
        (domain2_visible waypoint3 waypoint2)
        (domain2_visible waypoint1 waypoint0)
        (domain2_visible waypoint2 waypoint0)
        (domain2_visible waypoint1 waypoint2)
        (domain2_visible waypoint1 waypoint3)
        (domain2_visible waypoint0 waypoint2)
        (domain2_visible waypoint3 waypoint1)
        (domain2_visible waypoint2 waypoint3)
        (domain2_visible waypoint0 waypoint3)
        (domain2_at_soil_sample waypoint0)
        (domain2_at_rock_sample waypoint0)
        (domain2_at_lander general waypoint1)
        (domain2_channel_free general)
        (domain2_at rover0 waypoint0)
        (domain2_available rover0)
        (domain2_store_of rover0store rover0)
        (domain2_empty rover0store)
        (domain2_equipped_for_soil_analysis rover0)
        (domain2_equipped_for_rock_analysis rover0)
        (domain2_equipped_for_imaging rover0)
        (domain2_can_traverse rover0 waypoint0 waypoint2)
        (domain2_can_traverse rover0 waypoint3 waypoint0)
        (domain2_can_traverse rover0 waypoint0 waypoint1)
        (domain2_can_traverse rover0 waypoint1 waypoint0)
        (domain2_can_traverse rover0 waypoint2 waypoint0)
        (domain2_can_traverse rover0 waypoint0 waypoint3)
        (domain2_on_board camera0 rover0)
        (domain2_on_board camera1 rover0)
        (domain2_calibration_target camera0 objective0)
        (domain2_calibration_target camera1 objective1)
        (domain2_supports camera1 high_res)
        (domain2_supports camera0 colour)
        (domain2_supports camera0 high_res)
        (domain2_supports camera0 low_res)
        (domain2_visible_from objective1 waypoint1)
        (domain2_visible_from objective1 waypoint0)
        (domain2_visible_from objective0 waypoint0)
        (domain2_visible_from objective1 waypoint2)
    )

    (:goal
        (failed )
    )

    
    
    
)

