
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem p2-dungeon)
    (:domain Dungeon)

    (:objects
        green purple rainbow red yellow - colour
        c1222 c2122 c2223 c2232 c3242 - corridor
        key1 key2 key3 key4 - key
        loc-1-2 loc-2-1 loc-2-2 loc-2-3 loc-3-2 loc-4-2 - location
    )

    (:init
        (domain1_hero-at loc-2-2)
        (domain1_connected loc-2-2 c1222)
        (domain1_connected loc-3-2 c2232)
        (domain1_connected loc-2-2 c2232)
        (domain1_connected loc-3-2 c3242)
        (domain1_connected loc-2-2 c2223)
        (domain1_connected loc-4-2 c3242)
        (domain1_connected loc-2-3 c2223)
        (domain1_connected loc-2-1 c2122)
        (domain1_connected loc-2-2 c2122)
        (domain1_connected loc-1-2 c1222)
        (domain1_in key2 loc-1-2)
        (domain1_in key4 loc-2-3)
        (domain1_in key1 loc-2-1)
        (domain1_in key3 loc-2-2)
        (domain1_locked c2122 purple)
        (domain1_locked c3242 rainbow)
        (domain1_locked c2232 yellow)
        (domain1_locked c2223 green)
        (domain1_locked c1222 yellow)
        (domain1_arm-free )
        (domain1_key-colour key3 purple)
        (domain1_key-colour key4 yellow)
        (domain1_key-colour key1 green)
        (domain1_key-colour key2 rainbow)
        (domain1_two-use key4)
        (domain1_one-use key1)
        (domain1_one-use key3)
        (domain2_hero-at loc-2-2)
        (domain2_arm-free )
        (domain2_corridor-between loc-2-2 loc-3-2 c2232)
        (domain2_corridor-between loc-2-2 loc-1-2 c1222)
        (domain2_corridor-between loc-2-2 loc-2-1 c2122)
        (domain2_corridor-between loc-3-2 loc-2-2 c2232)
        (domain2_corridor-between loc-4-2 loc-3-2 c3242)
        (domain2_corridor-between loc-1-2 loc-2-2 c1222)
        (domain2_corridor-between loc-2-2 loc-2-3 c2223)
        (domain2_corridor-between loc-2-1 loc-2-2 c2122)
        (domain2_corridor-between loc-3-2 loc-4-2 c3242)
        (domain2_corridor-between loc-2-3 loc-2-2 c2223)
        (domain2_connected loc-2-2 c1222)
        (domain2_connected loc-3-2 c2232)
        (domain2_connected loc-2-2 c2223)
        (domain2_connected loc-2-2 c2232)
        (domain2_connected loc-3-2 c3242)
        (domain2_connected loc-4-2 c3242)
        (domain2_connected loc-2-3 c2223)
        (domain2_connected loc-1-2 c2122)
        (domain2_connected loc-2-2 c2122)
        (domain2_connected loc-1-2 c1222)
        (domain2_key-at key2 loc-1-2)
        (domain2_key-at key4 loc-2-3)
        (domain2_key-at key1 loc-2-1)
        (domain2_key-at key3 loc-2-2)
        (domain2_locked c3242)
        (domain2_locked c2122)
        (domain2_locked c2223)
        (domain2_locked c1222)
        (domain2_locked c2232)
        (domain2_lock-colour c2122 purple)
        (domain2_lock-colour c3242 rainbow)
        (domain2_lock-colour c2232 yellow)
        (domain2_lock-colour c2223 green)
        (domain2_lock-colour c1222 yellow)
        (domain2_key-colour key4 yellow)
        (domain2_key-colour key1 green)
        (domain2_key-colour key2 rainbow)
        (domain2_key-colour key3 purple)
        (domain2_key-usable key1)
        (domain2_key-usable key4)
        (domain2_key-usable key2)
        (domain2_key-usable key3)
        (domain2_key-single-use key1)
        (domain2_key-single-use key2)
        (domain2_key-single-use key3)
        (domain2_key-double-use key4)
    )

    (:goal
        (failed )
    )

    
    
    
)

